services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:80"
    environment:
      - DB_HOST=<db_ip>
      - DB_PORT=27017
      - DB_NAME=mongodb
      - DB_USER=<db_username>
      - DB_PASSWORD=<secure_db_password>
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<db_username>
      - MONGO_INITDB_ROOT_PASSWORD=<secure_db_password>
    volumes:
      - ./data:/data/db

volumes:
  data:
